// PASO 1
// BUSCO TODA LA INFORMACION BASICA EN CRIME_SCENE_REPORT

// PASO 2
// SABIENDO EL NOMBRE DE LAS COLUMNAS FILTRO SEGUN LA INFORMACION QUE TENGO EN EL COMIENZO DEL EJERCICIO QUE EL TIPO DE CRIMEN FUE "MURDER" Y EN LA CITY "SQL CITY"

// PASO 3
// BUSCO LA INFORMACION COMPLETA DEL PRIMER TESTIGO EN LA TABLA PERSON Y OBTENGO TODA SU INFORMACION PERSONAL

// PASO 4
// BUSCO LA INFORMACION DEL 2DO TESTIGO SABIENDO LA CALLE Y QUE VIVIA EN LA ULTIMA CASA DE NORTHWESTERN DR

// PASO 5
// BUSCO EL INTERROGATORIO DE ANNABEL EN LA TABLA INTERVIEW SEGUN EL ID QUE CONSEGUÍ EN LA PRIMERA BUSQUEDA

// PASO 6
// YA SABEMOS QUE RECONOCIO AL ASESINO EN SU GIMNASIO QUE FUE EL MISMO DIA, OBTENEMOS ACA EL ID DE MIEMBRO DEL GIMNASIO

// PASO 7
// EN EL CHECK_IN DEL GIMNASIO BUSCAMOS LAS PERSONAS QUE FUERON CON ELLA ESE MISMO DIA EMPEZAMOS EL SEGUIMIENTO CON EL PRIMER VALOR OBTENIDO

// PASO 8
// BUSCAMOS EL ID DE LA PERSON EN EL REGISTRO DEL GIMNASIO

// PASO 9
// SEGUN EL INTERVIEW DE SU ID OBTENEMOS UNA DECLARACION QUE ME PARECIO BASTANTE IMPORTANTE, DONDE DABA LA DESCRICION EXACTA DE UNA PERSONA SOSPECHOSA QUIEN HABIA CONTRATADO A ESA PERSONA

// PASO 10
// EN DRIVERS_LICENSE BUSCAMOS SEGUN MODELO DEL AUTO Y BUSCAMOS LOS RESULTADOS, FIJANDONOS EN LAS PERSONAS PELIRROJAS EN HAIR_COLOR, Y PROCEDO A BUSCAR EL PRIMER RESULTADO, QUE ME PARECIO EL QUE MAS COMPATIBILIZABA CON LA DESCRIPCION

// PASO 11
// EN EL CHECK IN DEL EVENTO SEGUN EL ID DE ESA PERSONA QUE OBTUVIMOS FILTRAMOS Y OBTENEMOS LA INFORMACION DE QUE SI ASISTIO AL EVENTO 3 VECES EN DICIEMBRE DEL 2017

// PASO 12
// SEGUN SI ID BUSCAMOS NOMBRE Y APELLIDO COMPLETO EN "PERSON"

// PASO 13
// CONSEGUIMOS LA ULTIMA COMPROBACION SABIENDO QUE SEGUN EL NUMERO SE SEGURIDAD SOCIAL (SSN) ERA LA MUJER PELIRROJA QUE MAS DINERO COBRABA ANUALMENTE DANDONOS ASI EL 100% DE COMPATIBILIDAD DE LA PERSONA QUE OMETIO EL CRIMEN

// PASO 14
// DAMOS LA COMPROBACION SEGUN NOMBRE Y APELLIDO QUE ES LA PERSONA QUE ESTUVIMOS BUSCANDO
